using Microsoft.EntityFrameworkCore;
using MiniSSO.Domain;
using MiniSSO.Services;

namespace MiniSSO.Data;

public static class Seeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await db.Database.EnsureCreatedAsync();

        if (db.Database.IsNpgsql())   // bảng thêm sau (License) — EnsureCreated không tạo trên Postgres đã tồn tại
        {
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Licenses\" (\"Id\" uuid PRIMARY KEY, \"LicenseKey\" text NOT NULL DEFAULT '', \"OwnerName\" text NOT NULL DEFAULT '', \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now(), \"ExpiresAt\" timestamp NULL)");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Licenses_LicenseKey\" ON minisso.\"Licenses\" (\"LicenseKey\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"LicenseCheckLogs\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"LicenseKey\" text NOT NULL DEFAULT '', \"AppSlug\" text NOT NULL DEFAULT '', \"InstanceHost\" text NULL, \"RemoteIp\" text NULL, \"Result\" boolean NOT NULL DEFAULT false, \"Message\" text NULL, \"CheckedAt\" timestamp NOT NULL DEFAULT now())");
            // RBAC theo nhóm (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Groups\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Description\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Groups_Code\" ON minisso.\"Groups\" (\"Code\")");
            // Đơn vị của nhóm (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Groups\" ADD COLUMN IF NOT EXISTS \"OrgId\" uuid NULL");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_Groups_OrgId\" ON minisso.\"Groups\" (\"OrgId\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"PermissionObjects\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Module\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_PermissionObjects_Code\" ON minisso.\"PermissionObjects\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"GroupMembers\" (\"Id\" uuid PRIMARY KEY, \"GroupId\" uuid NOT NULL, \"UserId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_GroupMembers_GroupId_UserId\" ON minisso.\"GroupMembers\" (\"GroupId\", \"UserId\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"GroupAccesses\" (\"Id\" uuid PRIMARY KEY, \"GroupId\" uuid NOT NULL, \"ObjectId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_GroupAccesses_GroupId_ObjectId\" ON minisso.\"GroupAccesses\" (\"GroupId\", \"ObjectId\")");
            // Cây tổ chức (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Orgs\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"ParentId\" uuid NULL, \"BuCode\" text NOT NULL DEFAULT '', \"BuPattern\" text NOT NULL DEFAULT '', \"Level\" integer NOT NULL DEFAULT 1, \"Remark\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Orgs_Code\" ON minisso.\"Orgs\" (\"Code\")");
            // Bảo mật tài khoản (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"FailedLoginCount\" integer NOT NULL DEFAULT 0");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"IsLockedOut\" boolean NOT NULL DEFAULT false");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"LockoutDate\" timestamp NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"LockoutUntil\" timestamp NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"VerificationCode\" text NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"LastLoginAt\" timestamp NULL");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"LoginAttempts\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Email\" text NOT NULL DEFAULT '', \"UserId\" uuid NULL, \"Success\" boolean NOT NULL DEFAULT false, \"Reason\" text NULL, \"RemoteIp\" text NULL, \"AttemptedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_LoginAttempts_AttemptedAt\" ON minisso.\"LoginAttempts\" (\"AttemptedAt\")");
            // Phạm vi dữ liệu (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"IsSysAdmin\" boolean NOT NULL DEFAULT false");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"OrgId\" uuid NULL");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_Users_OrgId\" ON minisso.\"Users\" (\"OrgId\")");
        }

        if (!await db.Licenses.AnyAsync())
        {
            db.Licenses.Add(new AppLicense { LicenseKey = "FLEET-DEFAULT-2026", OwnerName = "kientran1705 (fleet nội bộ)", IsActive = true });
            await db.SaveChangesAsync();
        }

        if (!await db.Users.AnyAsync())
        {
            db.Users.AddRange(
                new AppUser { Email = "admin@minisso.dev", FullName = "Quản trị hệ thống", Roles = "Admin", PasswordHash = PasswordHasher.Hash("Admin@123") },
                new AppUser { Email = "sales@minisso.dev", FullName = "Nhân viên Kinh doanh", Roles = "Sales", Tenant = "Demo", PasswordHash = PasswordHasher.Hash("Sales@123") },
                new AppUser { Email = "dealer@minisso.dev", FullName = "Đại lý Đông Đô", Roles = "Dealer", Tenant = "DongDo", PasswordHash = PasswordHasher.Hash("Dealer@123") });
            await db.SaveChangesAsync();
        }
        await SeedRbacAsync(db);
        await SeedOrgsAsync(db);
        await SeedDataScopeAsync(db);

        if (!await db.Clients.AnyAsync())
        {
            db.Clients.AddRange(
                // Client web (SPA/MVC): authorization_code + PKCE, không secret
                new Client { ClientId = "fleet-web", Name = "Fleet Web App", RequirePkce = true, ClientSecretHash = null,
                    RedirectUris = "http://localhost:5000/callback,https://oidcdebugger.com/debug",
                    AllowedGrants = "authorization_code,refresh_token", AllowedScopes = "openid,profile,email,roles" },
                // Client dịch vụ (server-to-server): password + client_credentials, có secret
                new Client { ClientId = "fleet-service", Name = "Fleet Service (M2M)", RequirePkce = false,
                    ClientSecretHash = PasswordHasher.Hash("service-secret-demo"),
                    RedirectUris = "", AllowedGrants = "password,client_credentials,refresh_token", AllowedScopes = "openid,profile,email,roles,api" });
            await db.SaveChangesAsync();
        }
    }

    /// <summary>Seed RBAC theo nhóm (port từ iNOS.InBrand): đối tượng quyền → nhóm → cấp quyền → thành viên.</summary>
    private static async Task SeedRbacAsync(AppDbContext db)
    {
        if (!await db.PermissionObjects.AnyAsync())
        {
            db.PermissionObjects.AddRange(
                new PermissionObject { Code = "user.manage", Name = "Quản lý người dùng", Module = "sso" },
                new PermissionObject { Code = "client.manage", Name = "Quản lý ứng dụng client", Module = "sso" },
                new PermissionObject { Code = "group.manage", Name = "Quản lý nhóm & phân quyền", Module = "sso" },
                new PermissionObject { Code = "license.view", Name = "Xem bản quyền & log", Module = "license" },
                new PermissionObject { Code = "report.view", Name = "Xem báo cáo", Module = "report" });
            await db.SaveChangesAsync();
        }

        if (!await db.Groups.AnyAsync())
        {
            db.Groups.AddRange(
                new Group { Code = "SYSADMIN", Name = "Quản trị hệ thống", Description = "Toàn quyền hệ thống" },
                new Group { Code = "SALES", Name = "Kinh doanh", Description = "Nhóm kinh doanh" },
                new Group { Code = "DEALER", Name = "Đại lý", Description = "Nhóm đại lý" });
            await db.SaveChangesAsync();
        }

        // Cấp quyền cho nhóm (Sys_Access): SYSADMIN toàn quyền, SALES/DEALER hạn chế.
        if (!await db.GroupAccesses.AnyAsync())
        {
            var objs = await db.PermissionObjects.ToDictionaryAsync(o => o.Code, o => o.Id);
            var grps = await db.Groups.ToDictionaryAsync(g => g.Code, g => g.Id);
            void Grant(string group, params string[] codes)
            {
                foreach (var c in codes)
                    db.GroupAccesses.Add(new GroupAccess { GroupId = grps[group], ObjectId = objs[c] });
            }
            Grant("SYSADMIN", "user.manage", "client.manage", "group.manage", "license.view", "report.view");
            Grant("SALES", "report.view");
            Grant("DEALER", "report.view");
            await db.SaveChangesAsync();
        }

        // Gán thành viên (Sys_UserInGroup): admin → SYSADMIN, sales → SALES, dealer → DEALER.
        if (!await db.GroupMembers.AnyAsync())
        {
            var users = await db.Users.ToDictionaryAsync(u => u.Email, u => u.Id);
            var grps = await db.Groups.ToDictionaryAsync(g => g.Code, g => g.Id);
            void Add(string email, string group)
            {
                if (users.TryGetValue(email, out var uid))
                    db.GroupMembers.Add(new GroupMember { UserId = uid, GroupId = grps[group] });
            }
            Add("admin@minisso.dev", "SYSADMIN");
            Add("sales@minisso.dev", "SALES");
            Add("dealer@minisso.dev", "DEALER");
            await db.SaveChangesAsync();
        }
    }

    /// <summary>Seed cây tổ chức (port từ iNOS.InBrand: Mst_Org) — 1 tập đoàn → công ty → chi nhánh/đại lý.</summary>
    private static async Task SeedOrgsAsync(AppDbContext db)
    {
        if (await db.Orgs.AnyAsync()) return;

        var root = new Org { Code = "0", Name = "Tập đoàn iNOS", Remark = "Nút gốc" };
        var north = new Org { Code = "10", Name = "Miền Bắc", ParentId = root.Id };
        var south = new Org { Code = "20", Name = "Miền Nam", ParentId = root.Id };
        var hn = new Org { Code = "11", Name = "Chi nhánh Hà Nội", ParentId = north.Id };
        var hcm = new Org { Code = "21", Name = "Chi nhánh Hồ Chí Minh", ParentId = south.Id };
        var dealer = new Org { Code = "211", Name = "Đại lý Đông Đô", ParentId = hcm.Id };
        db.Orgs.AddRange(root, north, south, hn, hcm, dealer);
        await db.SaveChangesAsync();

        // Tính BuCode/BuPattern/Level cho toàn cây (tương ứng Mst_Org_UpdBU).
        await new OrgService(db).RebuildPathsAsync();
    }

    /// <summary>
    /// Seed phạm vi dữ liệu (port từ iNOS.InBrand: SysUser.SysAdmin / SysUser.DLCode).
    /// Gắn mỗi người dùng vào 1 đơn vị tổ chức + cờ SysAdmin để minh hoạ 3 mức phạm vi:
    ///   • admin  → SysAdmin = true (thấy tất cả),
    ///   • sales  → đơn vị "Miền Bắc" (chỉ thấy nhánh Miền Bắc),
    ///   • dealer → đơn vị "Đại lý Đông Đô" (chỉ thấy chính nó).
    /// </summary>
    private static async Task SeedDataScopeAsync(AppDbContext db)
    {
        // Chỉ gán khi chưa có người dùng nào được gắn đơn vị (tránh ghi đè cấu hình thủ công).
        if (await db.Users.AnyAsync(u => u.OrgId != null || u.IsSysAdmin)) return;

        var orgs = await db.Orgs.ToDictionaryAsync(o => o.Code, o => o.Id);
        var users = await db.Users.ToDictionaryAsync(u => u.Email, u => u);

        if (users.TryGetValue("admin@minisso.dev", out var admin)) admin.IsSysAdmin = true;
        if (users.TryGetValue("sales@minisso.dev", out var sales) && orgs.TryGetValue("10", out var north)) sales.OrgId = north;
        if (users.TryGetValue("dealer@minisso.dev", out var dealer) && orgs.TryGetValue("211", out var dongDo)) dealer.OrgId = dongDo;

        await db.SaveChangesAsync();
    }
}
