using Microsoft.EntityFrameworkCore;
using MiniSSO.Domain;
using MiniSSO.Services;

namespace MiniSSO.Data;

public static class Seeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await db.Database.EnsureCreatedAsync();

        if (db.Database.IsNpgsql())   // bảng thêm sau (License) — EnsureCreated không tạo trên Postgres đã tồn tại
        {
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Licenses\" (\"Id\" uuid PRIMARY KEY, \"LicenseKey\" text NOT NULL DEFAULT '', \"OwnerName\" text NOT NULL DEFAULT '', \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now(), \"ExpiresAt\" timestamp NULL)");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Licenses_LicenseKey\" ON minisso.\"Licenses\" (\"LicenseKey\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"LicenseCheckLogs\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"LicenseKey\" text NOT NULL DEFAULT '', \"AppSlug\" text NOT NULL DEFAULT '', \"InstanceHost\" text NULL, \"RemoteIp\" text NULL, \"Result\" boolean NOT NULL DEFAULT false, \"Message\" text NULL, \"CheckedAt\" timestamp NOT NULL DEFAULT now())");
            // RBAC theo nhóm (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Groups\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Description\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Groups_Code\" ON minisso.\"Groups\" (\"Code\")");
            // Đơn vị của nhóm (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Groups\" ADD COLUMN IF NOT EXISTS \"OrgId\" uuid NULL");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_Groups_OrgId\" ON minisso.\"Groups\" (\"OrgId\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"PermissionObjects\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Module\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_PermissionObjects_Code\" ON minisso.\"PermissionObjects\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"GroupMembers\" (\"Id\" uuid PRIMARY KEY, \"GroupId\" uuid NOT NULL, \"UserId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_GroupMembers_GroupId_UserId\" ON minisso.\"GroupMembers\" (\"GroupId\", \"UserId\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"GroupAccesses\" (\"Id\" uuid PRIMARY KEY, \"GroupId\" uuid NOT NULL, \"ObjectId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_GroupAccesses_GroupId_ObjectId\" ON minisso.\"GroupAccesses\" (\"GroupId\", \"ObjectId\")");
            // Gán module trực tiếp cho nhóm (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"GroupModuleAccesses\" (\"Id\" uuid PRIMARY KEY, \"GroupId\" uuid NOT NULL, \"ModuleId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_GroupModuleAccesses_GroupId_ModuleId\" ON minisso.\"GroupModuleAccesses\" (\"GroupId\", \"ModuleId\")");
            // Cây tổ chức (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Orgs\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"ParentId\" uuid NULL, \"BuCode\" text NOT NULL DEFAULT '', \"BuPattern\" text NOT NULL DEFAULT '', \"Level\" integer NOT NULL DEFAULT 1, \"Remark\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Orgs_Code\" ON minisso.\"Orgs\" (\"Code\")");
            // Bảo mật tài khoản (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"FailedLoginCount\" integer NOT NULL DEFAULT 0");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"IsLockedOut\" boolean NOT NULL DEFAULT false");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"LockoutDate\" timestamp NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"LockoutUntil\" timestamp NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"VerificationCode\" text NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"LastLoginAt\" timestamp NULL");
            // Hồ sơ tự đăng ký (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"PhoneNo\" text NULL");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"Language\" text NOT NULL DEFAULT 'vi'");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"LoginAttempts\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Email\" text NOT NULL DEFAULT '', \"UserId\" uuid NULL, \"Success\" boolean NOT NULL DEFAULT false, \"Reason\" text NULL, \"RemoteIp\" text NULL, \"AttemptedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_LoginAttempts_AttemptedAt\" ON minisso.\"LoginAttempts\" (\"AttemptedAt\")");
            // Phạm vi dữ liệu (thêm sau) — EnsureCreated không thêm cột vào bảng đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"IsSysAdmin\" boolean NOT NULL DEFAULT false");
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE minisso.\"Users\" ADD COLUMN IF NOT EXISTS \"OrgId\" uuid NULL");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_Users_OrgId\" ON minisso.\"Users\" (\"OrgId\")");
            // Phân hệ chức năng Module → Function (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Modules\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Title\" text NOT NULL DEFAULT '', \"Description\" text NULL, \"ModuleType\" text NULL, \"ParentId\" uuid NULL, \"SortOrder\" integer NOT NULL DEFAULT 0, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Modules_Code\" ON minisso.\"Modules\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_Modules_ParentId\" ON minisso.\"Modules\" (\"ParentId\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"Functions\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Description\" text NOT NULL DEFAULT '', \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Functions_Code\" ON minisso.\"Functions\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"FunctionInModules\" (\"Id\" uuid PRIMARY KEY, \"ModuleId\" uuid NOT NULL, \"FunctionId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_FunctionInModules_ModuleId_FunctionId\" ON minisso.\"FunctionInModules\" (\"ModuleId\", \"FunctionId\")");
            // Nhóm cột hiển thị (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"ViewColumnViews\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Remark\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ViewColumnViews_Code\" ON minisso.\"ViewColumnViews\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"ViewGroupViews\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Remark\" text NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ViewGroupViews_Code\" ON minisso.\"ViewGroupViews\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"ViewColumnInGroups\" (\"Id\" uuid PRIMARY KEY, \"GroupViewId\" uuid NOT NULL, \"ColumnViewId\" uuid NOT NULL, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ViewColumnInGroups_GroupViewId_ColumnViewId\" ON minisso.\"ViewColumnInGroups\" (\"GroupViewId\", \"ColumnViewId\")");
            // Đội người dùng (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"UserTeams\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"OrgId\" uuid NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_UserTeams_Code\" ON minisso.\"UserTeams\" (\"Code\")");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE INDEX IF NOT EXISTS \"IX_UserTeams_OrgId\" ON minisso.\"UserTeams\" (\"OrgId\")");
            // Loại đại lý (thêm sau) — EnsureCreated không tạo trên Postgres đã tồn tại.
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS minisso.\"DealerTypes\" (\"Id\" uuid PRIMARY KEY, \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp NOT NULL DEFAULT now())");
            await db.Database.ExecuteSqlRawAsync(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_DealerTypes_Code\" ON minisso.\"DealerTypes\" (\"Code\")");
        }

        if (!await db.Licenses.AnyAsync())
        {
            db.Licenses.Add(new AppLicense { LicenseKey = "FLEET-DEFAULT-2026", OwnerName = "kientran1705 (fleet nội bộ)", IsActive = true });
            await db.SaveChangesAsync();
        }

        if (!await db.Users.AnyAsync())
        {
            db.Users.AddRange(
                new AppUser { Email = "admin@minisso.dev", FullName = "Quản trị hệ thống", Roles = "Admin", PasswordHash = PasswordHasher.Hash("Admin@123") },
                new AppUser { Email = "sales@minisso.dev", FullName = "Nhân viên Kinh doanh", Roles = "Sales", Tenant = "Demo", PasswordHash = PasswordHasher.Hash("Sales@123") },
                new AppUser { Email = "dealer@minisso.dev", FullName = "Đại lý Đông Đô", Roles = "Dealer", Tenant = "DongDo", PasswordHash = PasswordHasher.Hash("Dealer@123") });
            await db.SaveChangesAsync();
        }
        await SeedRbacAsync(db);
        await SeedOrgsAsync(db);
        await SeedDataScopeAsync(db);
        await SeedModulesAsync(db);
        await SeedGroupModulesAsync(db);
        await SeedViewGroupsAsync(db);
        await SeedUserTeamsAsync(db);
        await SeedDealerTypesAsync(db);

        if (!await db.Clients.AnyAsync())
        {
            db.Clients.AddRange(
                // Client web (SPA/MVC): authorization_code + PKCE, không secret
                new Client { ClientId = "fleet-web", Name = "Fleet Web App", RequirePkce = true, ClientSecretHash = null,
                    RedirectUris = "http://localhost:5000/callback,https://oidcdebugger.com/debug",
                    AllowedGrants = "authorization_code,refresh_token", AllowedScopes = "openid,profile,email,roles" },
                // Client dịch vụ (server-to-server): password + client_credentials, có secret
                new Client { ClientId = "fleet-service", Name = "Fleet Service (M2M)", RequirePkce = false,
                    ClientSecretHash = PasswordHasher.Hash("service-secret-demo"),
                    RedirectUris = "", AllowedGrants = "password,client_credentials,refresh_token", AllowedScopes = "openid,profile,email,roles,api" });
            await db.SaveChangesAsync();
        }
    }

    /// <summary>Seed RBAC theo nhóm (port từ iNOS.InBrand): đối tượng quyền → nhóm → cấp quyền → thành viên.</summary>
    private static async Task SeedRbacAsync(AppDbContext db)
    {
        if (!await db.PermissionObjects.AnyAsync())
        {
            db.PermissionObjects.AddRange(
                new PermissionObject { Code = "user.manage", Name = "Quản lý người dùng", Module = "sso" },
                new PermissionObject { Code = "client.manage", Name = "Quản lý ứng dụng client", Module = "sso" },
                new PermissionObject { Code = "group.manage", Name = "Quản lý nhóm & phân quyền", Module = "sso" },
                new PermissionObject { Code = "license.view", Name = "Xem bản quyền & log", Module = "license" },
                new PermissionObject { Code = "report.view", Name = "Xem báo cáo", Module = "report" });
            await db.SaveChangesAsync();
        }

        if (!await db.Groups.AnyAsync())
        {
            db.Groups.AddRange(
                new Group { Code = "SYSADMIN", Name = "Quản trị hệ thống", Description = "Toàn quyền hệ thống" },
                new Group { Code = "SALES", Name = "Kinh doanh", Description = "Nhóm kinh doanh" },
                new Group { Code = "DEALER", Name = "Đại lý", Description = "Nhóm đại lý" });
            await db.SaveChangesAsync();
        }

        // Cấp quyền cho nhóm (Sys_Access): SYSADMIN toàn quyền, SALES/DEALER hạn chế.
        if (!await db.GroupAccesses.AnyAsync())
        {
            var objs = await db.PermissionObjects.ToDictionaryAsync(o => o.Code, o => o.Id);
            var grps = await db.Groups.ToDictionaryAsync(g => g.Code, g => g.Id);
            void Grant(string group, params string[] codes)
            {
                foreach (var c in codes)
                    db.GroupAccesses.Add(new GroupAccess { GroupId = grps[group], ObjectId = objs[c] });
            }
            Grant("SYSADMIN", "user.manage", "client.manage", "group.manage", "license.view", "report.view");
            Grant("SALES", "report.view");
            Grant("DEALER", "report.view");
            await db.SaveChangesAsync();
        }

        // Gán thành viên (Sys_UserInGroup): admin → SYSADMIN, sales → SALES, dealer → DEALER.
        if (!await db.GroupMembers.AnyAsync())
        {
            var users = await db.Users.ToDictionaryAsync(u => u.Email, u => u.Id);
            var grps = await db.Groups.ToDictionaryAsync(g => g.Code, g => g.Id);
            void Add(string email, string group)
            {
                if (users.TryGetValue(email, out var uid))
                    db.GroupMembers.Add(new GroupMember { UserId = uid, GroupId = grps[group] });
            }
            Add("admin@minisso.dev", "SYSADMIN");
            Add("sales@minisso.dev", "SALES");
            Add("dealer@minisso.dev", "DEALER");
            await db.SaveChangesAsync();
        }
    }

    /// <summary>Seed cây tổ chức (port từ iNOS.InBrand: Mst_Org) — 1 tập đoàn → công ty → chi nhánh/đại lý.</summary>
    private static async Task SeedOrgsAsync(AppDbContext db)
    {
        if (await db.Orgs.AnyAsync()) return;

        var root = new Org { Code = "0", Name = "Tập đoàn iNOS", Remark = "Nút gốc" };
        var north = new Org { Code = "10", Name = "Miền Bắc", ParentId = root.Id };
        var south = new Org { Code = "20", Name = "Miền Nam", ParentId = root.Id };
        var hn = new Org { Code = "11", Name = "Chi nhánh Hà Nội", ParentId = north.Id };
        var hcm = new Org { Code = "21", Name = "Chi nhánh Hồ Chí Minh", ParentId = south.Id };
        var dealer = new Org { Code = "211", Name = "Đại lý Đông Đô", ParentId = hcm.Id };
        db.Orgs.AddRange(root, north, south, hn, hcm, dealer);
        await db.SaveChangesAsync();

        // Tính BuCode/BuPattern/Level cho toàn cây (tương ứng Mst_Org_UpdBU).
        await new OrgService(db).RebuildPathsAsync();
    }

    /// <summary>
    /// Seed phạm vi dữ liệu (port từ iNOS.InBrand: SysUser.SysAdmin / SysUser.DLCode).
    /// Gắn mỗi người dùng vào 1 đơn vị tổ chức + cờ SysAdmin để minh hoạ 3 mức phạm vi:
    ///   • admin  → SysAdmin = true (thấy tất cả),
    ///   • sales  → đơn vị "Miền Bắc" (chỉ thấy nhánh Miền Bắc),
    ///   • dealer → đơn vị "Đại lý Đông Đô" (chỉ thấy chính nó).
    /// </summary>
    private static async Task SeedDataScopeAsync(AppDbContext db)
    {
        // Chỉ gán khi chưa có người dùng nào được gắn đơn vị (tránh ghi đè cấu hình thủ công).
        if (await db.Users.AnyAsync(u => u.OrgId != null || u.IsSysAdmin)) return;

        var orgs = await db.Orgs.ToDictionaryAsync(o => o.Code, o => o.Id);
        var users = await db.Users.ToDictionaryAsync(u => u.Email, u => u);

        if (users.TryGetValue("admin@minisso.dev", out var admin)) admin.IsSysAdmin = true;
        if (users.TryGetValue("sales@minisso.dev", out var sales) && orgs.TryGetValue("10", out var north)) sales.OrgId = north;
        if (users.TryGetValue("dealer@minisso.dev", out var dealer) && orgs.TryGetValue("211", out var dongDo)) dealer.OrgId = dongDo;

        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Seed phân hệ chức năng (port từ iNOS.InBrand: SysModule / SysFunction / SysFunctionInModule).
    /// Dựng cây module (sso → user/group/org) + chức năng con, và gắn chức năng vào module.
    /// Module.Code trùng với PermissionObject.Module để "menu hiệu lực" suy ra được từ quyền nhóm.
    /// </summary>
    private static async Task SeedModulesAsync(AppDbContext db)
    {
        if (await db.Modules.AnyAsync()) return;

        var sso = new Module { Code = "sso", Title = "Định danh & Phân quyền", ModuleType = "MENU", SortOrder = 1 };
        var license = new Module { Code = "license", Title = "Bản quyền", ModuleType = "MENU", SortOrder = 2 };
        var report = new Module { Code = "report", Title = "Báo cáo", ModuleType = "MENU", SortOrder = 3 };
        var user = new Module { Code = "sso.user", Title = "Người dùng", ModuleType = "PAGE", ParentId = sso.Id, SortOrder = 1 };
        var group = new Module { Code = "sso.group", Title = "Nhóm & Phân quyền", ModuleType = "PAGE", ParentId = sso.Id, SortOrder = 2 };
        var org = new Module { Code = "sso.org", Title = "Tổ chức", ModuleType = "PAGE", ParentId = sso.Id, SortOrder = 3 };
        db.Modules.AddRange(sso, license, report, user, group, org);
        await db.SaveChangesAsync();

        var fCreate = new Function { Code = "user.create", Description = "Tạo người dùng" };
        var fLock = new Function { Code = "user.lock", Description = "Khoá/mở khoá tài khoản" };
        var fReset = new Function { Code = "user.reset", Description = "Đặt lại mật khẩu" };
        var fGrant = new Function { Code = "group.grant", Description = "Cấp/thu quyền nhóm" };
        var fMember = new Function { Code = "group.member", Description = "Thêm/bớt thành viên nhóm" };
        var fOrgCreate = new Function { Code = "org.create", Description = "Tạo đơn vị tổ chức" };
        db.Functions.AddRange(fCreate, fLock, fReset, fGrant, fMember, fOrgCreate);
        await db.SaveChangesAsync();

        void Link(Module m, params Function[] fns)
        {
            foreach (var f in fns)
                db.FunctionInModules.Add(new FunctionInModule { ModuleId = m.Id, FunctionId = f.Id });
        }
        Link(user, fCreate, fLock, fReset);
        Link(group, fGrant, fMember);
        Link(org, fOrgCreate);
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Seed gán module trực tiếp cho nhóm (port từ iNOS.InBrand: Sys_Access = GroupCode + ModuleCode).
    /// SYSADMIN được cấp toàn bộ module; SALES chỉ được cấp module báo cáo.
    /// </summary>
    private static async Task SeedGroupModulesAsync(AppDbContext db)
    {
        if (await db.GroupModuleAccesses.AnyAsync()) return;

        var grps = await db.Groups.ToDictionaryAsync(g => g.Code, g => g.Id);
        var mods = await db.Modules.ToDictionaryAsync(m => m.Code, m => m.Id);
        void Grant(string group, params string[] codes)
        {
            if (!grps.TryGetValue(group, out var gid)) return;
            foreach (var c in codes)
                if (mods.TryGetValue(c, out var mid))
                    db.GroupModuleAccesses.Add(new GroupModuleAccess { GroupId = gid, ModuleId = mid });
        }
        Grant("SYSADMIN", "sso", "license", "report", "sso.user", "sso.group", "sso.org");
        Grant("SALES", "report");
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Seed nhóm cột hiển thị (port từ iNOS.InBrand: View_ColumnView / View_GroupView / View_ColumnInGroup).
    /// Tạo danh mục cột hiển thị + 2 nhóm (GRID_SALE, GRID_ADMIN) và gán cột vào nhóm.
    /// </summary>
    private static async Task SeedViewGroupsAsync(AppDbContext db)
    {
        if (await db.ViewColumnViews.AnyAsync()) return;

        var cCode = new ViewColumnView { Code = "col.code", Name = "Mã" };
        var cName = new ViewColumnView { Code = "col.name", Name = "Tên" };
        var cOrg = new ViewColumnView { Code = "col.org", Name = "Đơn vị" };
        var cStatus = new ViewColumnView { Code = "col.status", Name = "Trạng thái" };
        var cCreated = new ViewColumnView { Code = "col.created", Name = "Ngày tạo" };
        db.ViewColumnViews.AddRange(cCode, cName, cOrg, cStatus, cCreated);
        await db.SaveChangesAsync();

        var sale = new ViewGroupView { Code = "GRID_SALE", Name = "Lưới kinh doanh" };
        var admin = new ViewGroupView { Code = "GRID_ADMIN", Name = "Lưới quản trị" };
        db.ViewGroupViews.AddRange(sale, admin);
        await db.SaveChangesAsync();

        void Link(ViewGroupView g, params ViewColumnView[] cols)
        {
            foreach (var c in cols)
                db.ViewColumnInGroups.Add(new ViewColumnInGroup { GroupViewId = g.Id, ColumnViewId = c.Id });
        }
        Link(sale, cCode, cName, cStatus);
        Link(admin, cCode, cName, cOrg, cStatus, cCreated);
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Seed đội người dùng (port từ iNOS.InBrand: Sys_UserTeam).
    /// Tạo vài đội gắn vào các đơn vị tổ chức sẵn có (Miền Bắc, Đại lý Đông Đô) + 1 đội toàn cục.
    /// </summary>
    private static async Task SeedUserTeamsAsync(AppDbContext db)
    {
        if (await db.UserTeams.AnyAsync()) return;

        var orgs = await db.Orgs.ToDictionaryAsync(o => o.Code, o => o.Id);
        var teams = new List<UserTeam>
        {
            new() { Code = "TEAM_HN1", Name = "Đội kinh doanh Hà Nội 1" },
            new() { Code = "TEAM_HN2", Name = "Đội kinh doanh Hà Nội 2" },
            new() { Code = "TEAM_DD1", Name = "Đội đại lý Đông Đô" },
        };
        if (orgs.TryGetValue("10", out var north)) teams[0].OrgId = north;
        if (orgs.TryGetValue("10", out var north2)) teams[1].OrgId = north2;
        if (orgs.TryGetValue("211", out var dongDo)) teams[2].OrgId = dongDo;
        db.UserTeams.AddRange(teams);
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Seed loại đại lý (port từ iNOS.InBrand: Mst_DealerType).
    /// Tạo vài loại phân loại đơn vị/đại lý (cấp 1, cấp 2, đại lý uỷ quyền).
    /// </summary>
    private static async Task SeedDealerTypesAsync(AppDbContext db)
    {
        if (await db.DealerTypes.AnyAsync()) return;

        db.DealerTypes.AddRange(
            new DealerType { Code = "DL_TYPE_1", Name = "Đại lý cấp 1" },
            new DealerType { Code = "DL_TYPE_2", Name = "Đại lý cấp 2" },
            new DealerType { Code = "DL_TYPE_AUTH", Name = "Đại lý uỷ quyền" });
        await db.SaveChangesAsync();
    }
}
